spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/swp391
  username: postgres
  password: admin

 main:
  allow-circular-references: true

 jpa:
  show-sql: true
  generate-ddl: true
  hibernate:
   ddl-auto: create-drop
 mvc:
  pathmatch:
   matching-strategy: ant_path_matcher
 jackson:
  serialization:
   fail-on-empty-beans: false


amazonProperties:
 endpointUrl: https://s3.us-east-1.amazonaws.com
 accessKey: AKIAVV3UDQR2ZNQ44OGP
 secretKey: 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
 bucketName: swp-391
 region: us-east-1